name: SpawnerProtection
version: 2.0
main: me.qball.spawnerprotection.SpawnerProtection
authors: [Qball]
description: Protect user placed spawners
Depend: [Vault]
commands:
   spawners:
    description: Base command
permissions:
     spawnerprotection.protect.reload:
        description: Allows someone to reload config
     spawnerprotection.protect.admin:
        description: Admin bypass permsission
     spawnerprotection.spawners.get:
        description: Allows access to /spawners get
     spawnerprotections.spawners.buy:
        description: Base permission needed to have access to /spawners buy
     spawnerprotection.spawners.buy.*:
        description: Permsission to buy any spawner
     spawnerprotection.spawners.buy.bat:
        description: Permsission to buy bat spawner
     spawnerprotection.spawners.buy.blaze:
        description: Permsission to buy blaze spawner
     spawnerprotection.spawners.buy.chicken:
        description: Permsission to buy chicken spawner
     spawnerprotection.spawners.buy.cow:
        description: Permsission to buy cow spawner
     spawnerprotection.spawners.buy.creeper:
        description: Permsission to buy creeper spawner
     spawnerprotection.spawners.buy.enderman:
        description: Permsission to buy enderman spawner
     spawnerprotection.spawners.buy.endermite:
        description: Permsission to buy endermite spawner
     spawnerprotection.spawners.buy.ghast:
        description: Permsission to buy ghat spawner
     spawnerprotection.spawners.buy.guardian:
        description: Permsission to buy guardian spawner
     spawnerprotection.spawners.buy.pig:
        description: Permsission to buy pig spawner
     spawnerprotection.spawners.buy.rabbit:
        description: Permsission to buy rabbit spawner
     spawnerprotection.spawners.buy.sheep:
        description: Permsission to buy sheep spawner
     spawnerprotection.spawners.buy.silverfish:
        description: Permsission to buy silverfish spawner
     spawnerprotection.spawners.buy.skeleton:
        description: Permsission to buy skeleton spawner
     spawnerprotection.spawners.buy.spider:
        description: Permsission to buy spider spawner
     spawnerprotection.spawners.buy.squid:
        description: Permsission to buy squic spawner
     spawnerprotection.spawners.buy.slime:
        description: Permsission to buy slime spawner
     spawnerprotection.spawners.buy.villager:
        description: Permsission to buy villager spawner
     spawnerprotection.spawners.buy.witch:
        description: Permsission to buy witch spawner
     spawnerprotection.spawners.buy.wolf:
        description: Permsission to buy wolf spawner
     spawnerprotection.spawners.buy.cavespider:
        description: Permsission to buy cavespider spawner
     spawnerprotection.spawners.buy.zombie:
        description: Permsission to buy zombie spawner
     spawnerprotection.spawners.buy.enderdragon:
        description: Permsission to buy enderdragon spawner
     spawnerprotection.spawners.buy.giant:
        description: Permsission to buy giant spawner
     spawnerprotection.spawners.buy.snowman:
        description: Permsission to buy snowman spawner
     spawnerprotection.spawners.buy.horse:
        description: Permsission to buy horse spawner
     spawnerprotection.spawners.buy.mooshroom:
        description: Permsission to buy mooshroom spawner
     spawnerprotection.spawners.buy.ocelot:
        description: Permsission to buy ocelot spawner
     spawnerprotection.spawners.buy.pigman:
        description: Permsission to buy pigman spawner
     spawnerprotection.spawners.buy.magmacube:
        description: Permsission to buy magmacube spawner
     spawnerprotection.spawners.buy.wither:
        description: Permsission to buy wither spawner
     spawnerprotection.spawners.buy.irongolem:
        description: Permsission to buy irongolem spawner
     spawnerprotection.spawners.buy.shulker:
        description: Permsission to buy shulker spawner
     spawnerprotection.spawners.buy.polarbear:
        description: Permsission to buy polarbeat spawner
     spawnerprotection.spawners.buy.llama:
        description: Permsission to buy llama spawner


